<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-9HG1TI6" failures="1" tests="9" name="Personal Loan" time="0.576" errors="0" timestamp="2024-12-07T09:21:16 IST">
  <testcase classname="test.day2" name="secondTest" time="0.026"/>
  <testcase classname="test.day3" name="MobileLoginCarLoan" time="0.007"/>
  <testcase classname="test.day3" name="MobilesignoutCarLoan" time="0.013"/>
  <testcase classname="test.day1" name="firstTest" time="0.103">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.firstTest(day1.java:20)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- firstTest -->
  <testcase classname="test.day3" name="WebLoginCarLoan" time="0.01"/>
  <testcase classname="test.day3" name="dataProviderCarLoan" time="0.005"/>
  <testcase classname="test.day3" name="dataProviderCarLoan" time="0.005"/>
  <testcase classname="test.day3" name="dataProviderCarLoan" time="0.003"/>
  <testcase classname="test.day3" name="LoginAPICarLoan" time="0.005"/>
  <testcase classname="test.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
  <testcase classname="test.day3" name="MobilesigninCarLoan" time="0.0">
    <ignored/>
  </testcase> <!-- MobilesigninCarLoan -->
</testsuite> <!-- Personal Loan -->
